import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type Language = 'fr' | 'ar' | 'en';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private languageSubject = new BehaviorSubject<Language>('fr');
  currentLanguage$ = this.languageSubject.asObservable();

  // Dictionnaires de traduction
  private translations: { [key: string]: { [key: string]: string } } = {
    fr: {
      // Français (langue par défaut)
      'dashboard': 'Tableau de bord',
      'settings': 'Paramètres',
      'appearance': 'Apparence',
      'darkMode': 'Mode sombre',
      'changeAppearance': 'Changer l\'apparence de l\'application',
      'language': 'Langue',
      'profile': 'Profil utilisateur',
      'editProfile': 'Modifier le profil',
      'changePassword': 'Changer le mot de passe',
      'notifications': 'Notifications',
      'emailNotifications': 'Notifications par email',
      'pushNotifications': 'Notifications push',
      'receivingReminders': 'Recevoir des rappels de rendez-vous',
      'appAlerts': 'Alertes dans l\'application',
      'doctor': 'Dr.',
      'generalPractitioner': 'Médecin généraliste',
      'appName': 'Cabinet Médical',
      'welcomeMessage': 'Bienvenue sur votre espace personnel',
      'patients': 'Patients',
      'appointments': 'Rendez-vous',
      'calendar': 'Calendrier',
      'todayAppointments': 'Rendez-vous du jour',
      'upcomingAppointments': 'Prochains rendez-vous',
      'patientsList': 'Liste des patients',
      'addPatient': 'Ajouter un patient',
      'search': 'Rechercher',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'logout': 'Déconnexion',
      'home': 'Accueil',
      'male': 'Homme',
      'female': 'Femme',
      'years': 'ans',
      'confirmed': 'Confirmé',
      'pending': 'En attente',
      'cancelled': 'Annulé',
      'noAppointmentsToday': 'Aucun rendez-vous pour aujourd\'hui',
      'noAppointmentsTomorrow': 'Aucun rendez-vous pour demain',
      'tomorrowAppointments': 'Rendez-vous de demain',
      'editPatient': 'Modifier le patient',
      'addNewPatient': 'Ajouter un nouveau patient',
      'patientPhoto': 'Photo du patient',
      'chooseImage': 'Choisir une image',
      'lastName': 'Nom',
      'firstName': 'Prénom',
      'patientLastName': 'Nom du patient',
      'patientFirstName': 'Prénom du patient',
      'pleaseEnterLastName': 'Veuillez saisir un nom',
      'pleaseEnterFirstName': 'Veuillez saisir un prénom',
      'age': 'Âge',
      'patientAge': 'Âge du patient',
      'pleaseEnterValidAge': 'Veuillez saisir un âge valide',
      'gender': 'Genre',
      'select': 'Sélectionner',
      'pleaseSelectGender': 'Veuillez sélectionner un genre',
      'phone': 'Téléphone',
      'phoneNumber': 'Numéro de téléphone',
      'pleaseEnterValidPhone': 'Veuillez saisir un numéro de téléphone valide (10 chiffres)',
      'cin': 'CIN',
      'nationalIDCard': 'Carte d\'identité nationale',
      'pleaseEnterValidCIN': 'Veuillez saisir un CIN valide',
      'braceletCode': 'Code Bracelet',
      'pleaseEnterBraceletCode': 'Veuillez saisir un code de bracelet',
      'update': 'Mettre à jour',
      'add': 'Ajouter',
      'appointmentsCalendar': 'Calendrier des Rendez-vous',
      'today': 'Aujourd\'hui',
      'month': 'Mois',
      'week': 'Semaine',
      'day': 'Jour',
      'monday': 'Lundi',
      'tuesday': 'Mardi',
      'wednesday': 'Mercredi',
      'thursday': 'Jeudi',
      'friday': 'Vendredi',
      'saturday': 'Samedi',
      'sunday': 'Dimanche',
      'edit': 'Modifier',
      'markPending': 'Mettre en attente',
      'confirm': 'Confirmer',
      'more': 'plus',
      'confirmedAppointment': 'Rendez-vous confirmé',
      'pendingConfirmation': 'En attente de confirmation',
      'cancelledAppointment': 'Rendez-vous annulé',
      'appointmentsFor': 'Rendez-vous du',
      'patient': 'Patient',
      'editAppointment': 'Modifier le rendez-vous',
      'newAppointment': 'Nouveau rendez-vous',
      'selectPatient': 'Sélectionner un patient',
      'pleaseSelectPatient': 'Veuillez sélectionner un patient.',
      'title': 'Titre',
      'appointmentTitlePlaceholder': 'Ex: Consultation, Suivi...',
      'titleRequired': 'Le titre est obligatoire.',
      'date': 'Date',
      'dateRequired': 'La date est obligatoire.',
      'status': 'Statut',
      'startTime': 'Heure de début',
      'startTimeRequired': 'L\'heure de début est obligatoire.',
      'endTime': 'Heure de fin',
      'endTimeRequired': 'L\'heure de fin est obligatoire.',
      'description': 'Description',
      'additionalInfo': 'Informations supplémentaires...',
      'patientDetails': 'Détails du patient',
      'patientNotFound': 'Patient non trouvé',
      'patientWithIdNotExist': 'Le patient avec l\'ID',
      'backToDashboard': 'Retour au tableau de bord',
      'heartRate': 'Rythme cardiaque',
      'oxygen': 'Oxygène',
      'temperature': 'Température',
      'noDataAvailable': 'Données non disponibles',
      'oxygenLevel': 'Niveau d\'oxygène',
      'medicalReport': 'Rapport Médical',
      'print': 'Imprimer',
      'medicalNotesAndObservations': 'Notes et observations médicales',
      'enterClinicalObservations': 'Saisissez ici vos observations cliniques, diagnostics et recommandations...',
      'saveReport': 'Enregistrer le rapport',
      'loadingPatientDetails': 'Chargement des détails du patient...',
      'personalInformation': 'Informations personnelles',
      'fullName': 'Nom complet',
      'history': 'Historique',
      'creationDate': 'Date de création',
      'lastModification': 'Dernière modification',
      'categories': 'Catégories',
      'newMessage': 'Nouveau message de John',
      'orderShipped': 'Votre commande a été expédiée',
      'newComment': 'Nouveau commentaire sur votre publication',
      'updateAvailable': 'Mise à jour disponible pour votre application',
      'meetingReminder': 'Rappel: Réunion à 15h',
      'myProfile': 'Mon Profil'
    },
    en: {
      'dashboard': 'Dashboard',
      'settings': 'Settings',
      'appearance': 'Appearance',
      'darkMode': 'Dark Mode',
      'changeAppearance': 'Change application appearance',
      'language': 'Language',
      'profile': 'User Profile',
      'editProfile': 'Edit Profile',
      'changePassword': 'Change Password',
      'notifications': 'Notifications',
      'emailNotifications': 'Email Notifications',
      'pushNotifications': 'Push Notifications',
      'receivingReminders': 'Receive appointment reminders',
      'appAlerts': 'In-app alerts',
      'doctor': 'Dr.',
      'generalPractitioner': 'General Practitioner',
      'appName': 'Medical Office',
      'welcomeMessage': 'Welcome to your personal space',
      'patients': 'Patients',
      'appointments': 'Appointments',
      'calendar': 'Calendar',
      'todayAppointments': 'Today\'s appointments',
      'upcomingAppointments': 'Upcoming appointments',
      'patientsList': 'Patients list',
      'addPatient': 'Add patient',
      'search': 'Search',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'logout': 'Logout',
      'home': 'Home',
      'male': 'Male',
      'female': 'Female',
      'years': 'years',
      'confirmed': 'Confirmed',
      'pending': 'Pending',
      'cancelled': 'Cancelled',
      'noAppointmentsToday': 'No appointments for today',
      'noAppointmentsTomorrow': 'No appointments for tomorrow',
      'tomorrowAppointments': 'Tomorrow\'s appointments',
      'editPatient': 'Edit patient',
      'addNewPatient': 'Add new patient',
      'patientPhoto': 'Patient photo',
      'chooseImage': 'Choose image',
      'lastName': 'Last name',
      'firstName': 'First name',
      'patientLastName': 'Patient last name',
      'patientFirstName': 'Patient first name',
      'pleaseEnterLastName': 'Please enter a last name',
      'pleaseEnterFirstName': 'Please enter a first name',
      'age': 'Age',
      'patientAge': 'Patient age',
      'pleaseEnterValidAge': 'Please enter a valid age',
      'gender': 'Gender',
      'select': 'Select',
      'pleaseSelectGender': 'Please select a gender',
      'phone': 'Phone',
      'phoneNumber': 'Phone number',
      'pleaseEnterValidPhone': 'Please enter a valid phone number (10 digits)',
      'cin': 'National ID',
      'nationalIDCard': 'National ID card',
      'pleaseEnterValidCIN': 'Please enter a valid national ID',
      'braceletCode': 'Bracelet code',
      'pleaseEnterBraceletCode': 'Please enter a bracelet code',
      'update': 'Update',
      'add': 'Add',
      'appointmentsCalendar': 'Appointments Calendar',
      'today': 'Today',
      'month': 'Month',
      'week': 'Week',
      'day': 'Day',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
      'edit': 'Edit',
      'markPending': 'Mark as pending',
      'confirm': 'Confirm',
      'more': 'more',
      'confirmedAppointment': 'Confirmed appointment',
      'pendingConfirmation': 'Awaiting confirmation',
      'cancelledAppointment': 'Cancelled appointment',
      'appointmentsFor': 'Appointments for',
      'patient': 'Patient',
      'editAppointment': 'Edit appointment',
      'newAppointment': 'New appointment',
      'selectPatient': 'Select a patient',
      'pleaseSelectPatient': 'Please select a patient.',
      'title': 'Title',
      'appointmentTitlePlaceholder': 'Ex: Consultation, Follow-up...',
      'titleRequired': 'Title is required.',
      'date': 'Date',
      'dateRequired': 'Date is required.',
      'status': 'Status',
      'startTime': 'Start time',
      'startTimeRequired': 'Start time is required.',
      'endTime': 'End time',
      'endTimeRequired': 'End time is required.',
      'description': 'Description',
      'additionalInfo': 'Additional information...',
      'patientDetails': 'Patient Details',
      'patientNotFound': 'Patient Not Found',
      'patientWithIdNotExist': 'The patient with ID',
      'backToDashboard': 'Back to Dashboard',
      'heartRate': 'Heart Rate',
      'oxygen': 'Oxygen',
      'temperature': 'Temperature',
      'noDataAvailable': 'No data available',
      'oxygenLevel': 'Oxygen Level',
      'medicalReport': 'Medical Report',
      'print': 'Print',
      'medicalNotesAndObservations': 'Medical notes and observations',
      'enterClinicalObservations': 'Enter your clinical observations, diagnoses and recommendations here...',
      'saveReport': 'Save Report',
      'loadingPatientDetails': 'Loading patient details...',
      'personalInformation': 'Personal Information',
      'fullName': 'Full Name',
      'history': 'History',
      'creationDate': 'Creation Date',
      'lastModification': 'Last Modification',
      'categories': 'Categories',
      'newMessage': 'New message from John',
      'orderShipped': 'Your order has been shipped',
      'newComment': 'New comment on your post',
      'updateAvailable': 'Update available for your app',
      'meetingReminder': 'Reminder: Meeting at 3PM',
      'myProfile': 'My Profile'
    },
    ar: {
      'dashboard': 'لوحة القيادة',
      'settings': 'الإعدادات',
      'appearance': 'المظهر',
      'darkMode': 'الوضع المظلم',
      'changeAppearance': 'تغيير مظهر التطبيق',
      'language': 'اللغة',
      'profile': 'الملف الشخصي',
      'editProfile': 'تعديل الملف الشخصي',
      'changePassword': 'تغيير كلمة المرور',
      'notifications': 'الإشعارات',
      'emailNotifications': 'إشعارات البريد الإلكتروني',
      'pushNotifications': 'الإشعارات المباشرة',
      'receivingReminders': 'استلام تذكيرات المواعيد',
      'appAlerts': 'تنبيهات التطبيق',
      'doctor': 'د.',
      'generalPractitioner': 'طبيب عام',
      'appName': 'العيادة الطبية',
      'welcomeMessage': 'مرحبًا بك في مساحتك الشخصية',
      'patients': 'المرضى',
      'appointments': 'المواعيد',
      'calendar': 'التقويم',
      'todayAppointments': 'مواعيد اليوم',
      'upcomingAppointments': 'المواعيد القادمة',
      'patientsList': 'قائمة المرضى',
      'addPatient': 'إضافة مريض',
      'search': 'بحث',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'logout': 'تسجيل الخروج',
      'home': 'الرئيسية',
      'male': 'ذكر',
      'female': 'أنثى',
      'years': 'سنوات',
      'confirmed': 'مؤكد',
      'pending': 'قيد الانتظار',
      'cancelled': 'ملغى',
      'noAppointmentsToday': 'لا توجد مواعيد لهذا اليوم',
      'noAppointmentsTomorrow': 'لا توجد مواعيد للغد',
      'tomorrowAppointments': 'مواعيد الغد',
      'editPatient': 'تعديل المريض',
      'addNewPatient': 'إضافة مريض جديد',
      'patientPhoto': 'صورة المريض',
      'chooseImage': 'اختر صورة',
      'lastName': 'اللقب',
      'firstName': 'الاسم',
      'patientLastName': 'لقب المريض',
      'patientFirstName': 'اسم المريض',
      'pleaseEnterLastName': 'الرجاء إدخال اللقب',
      'pleaseEnterFirstName': 'الرجاء إدخال الاسم',
      'age': 'العمر',
      'patientAge': 'عمر المريض',
      'pleaseEnterValidAge': 'الرجاء إدخال عمر صحيح',
      'gender': 'الجنس',
      'select': 'اختر',
      'pleaseSelectGender': 'الرجاء اختيار الجنس',
      'phone': 'الهاتف',
      'phoneNumber': 'رقم الهاتف',
      'pleaseEnterValidPhone': 'الرجاء إدخال رقم هاتف صحيح (10 أرقام)',
      'cin': 'البطاقة الوطنية',
      'nationalIDCard': 'بطاقة التعريف الوطنية',
      'pleaseEnterValidCIN': 'الرجاء إدخال بطاقة تعريف وطنية صالحة',
      'braceletCode': 'رمز السوار',
      'pleaseEnterBraceletCode': 'الرجاء إدخال رمز السوار',
      'update': 'تحديث',
      'add': 'إضافة',
      'appointmentsCalendar': 'تقويم المواعيد',
      'today': 'اليوم',
      'month': 'شهر',
      'week': 'أسبوع',
      'day': 'يوم',
      'monday': 'الإثنين',
      'tuesday': 'الثلاثاء',
      'wednesday': 'الأربعاء',
      'thursday': 'الخميس',
      'friday': 'الجمعة',
      'saturday': 'السبت',
      'sunday': 'الأحد',
      'edit': 'تعديل',
      'markPending': 'تعليق',
      'confirm': 'تأكيد',
      'more': 'المزيد',
      'confirmedAppointment': 'موعد مؤكد',
      'pendingConfirmation': 'في انتظار التأكيد',
      'cancelledAppointment': 'موعد ملغى',
      'appointmentsFor': 'مواعيد يوم',
      'patient': 'المريض',
      'editAppointment': 'تعديل الموعد',
      'newAppointment': 'موعد جديد',
      'selectPatient': 'اختر مريضًا',
      'pleaseSelectPatient': 'الرجاء اختيار مريض',
      'title': 'العنوان',
      'appointmentTitlePlaceholder': 'مثال: استشارة، متابعة...',
      'titleRequired': 'العنوان مطلوب',
      'date': 'التاريخ',
      'dateRequired': 'التاريخ مطلوب',
      'status': 'الحالة',
      'startTime': 'وقت البدء',
      'startTimeRequired': 'وقت البدء مطلوب',
      'endTime': 'وقت الانتهاء',
      'endTimeRequired': 'وقت الانتهاء مطلوب',
      'description': 'الوصف',
      'additionalInfo': 'معلومات إضافية...',
      'patientDetails': 'تفاصيل المريض',
      'patientNotFound': 'المريض غير موجود',
      'patientWithIdNotExist': 'المريض برقم التعريف',
      'backToDashboard': 'العودة إلى لوحة التحكم',
      'heartRate': 'معدل ضربات القلب',
      'oxygen': 'الأكسجين',
      'temperature': 'درجة الحرارة',
      'noDataAvailable': 'لا توجد بيانات متاحة',
      'oxygenLevel': 'مستوى الأكسجين',
      'medicalReport': 'التقرير الطبي',
      'print': 'طباعة',
      'medicalNotesAndObservations': 'ملاحظات ومشاهدات طبية',
      'enterClinicalObservations': 'أدخل ملاحظاتك السريرية والتشخيصات والتوصيات هنا...',
      'saveReport': 'حفظ التقرير',
      'loadingPatientDetails': 'جاري تحميل تفاصيل المريض...',
      'personalInformation': 'معلومات شخصية',
      'fullName': 'الاسم الكامل',
      'history': 'السجل',
      'creationDate': 'تاريخ الإنشاء',
      'lastModification': 'آخر تعديل',
      'categories': 'الفئات',
      'newMessage': 'رسالة جديدة من جون',
      'orderShipped': 'تم شحن طلبك',
      'newComment': 'تعليق جديد على منشورك',
      'updateAvailable': 'تحديث متاح لتطبيقك',
      'meetingReminder': 'تذكير: اجتماع الساعة 3 مساءً',
      'myProfile': 'ملفي الشخصي'
    }
  };

  constructor() {
    // Récupérer la langue du localStorage si elle existe
    const savedLanguage = localStorage.getItem('appLanguage');
    if (savedLanguage && (savedLanguage === 'fr' || savedLanguage === 'en' || savedLanguage === 'ar')) {
      this.languageSubject.next(savedLanguage as Language);
      document.documentElement.lang = savedLanguage;
      document.documentElement.dir = savedLanguage === 'ar' ? 'rtl' : 'ltr';
    }
  }

  setLanguage(lang: Language): void {
    this.languageSubject.next(lang);
    // Sauvegarder la langue dans le localStorage
    localStorage.setItem('appLanguage', lang);
    
    // Définir la langue du document pour l'accessibilité
    document.documentElement.lang = lang;
    
    // Définir la direction du texte pour l'arabe (droite à gauche)
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }

  // Méthode pour obtenir la traduction d'une clé
  translate(key: string): string {
    const currentLang = this.languageSubject.value;
    return this.translations[currentLang][key] || key;
  }
} 